### ISSUE TITLE
Cannot download sources for the dependencies?

### ISSUE THREAD

**Issue by gallardo** [hildo/netbeans-gradle-javaee-project#19]
NetBeans do not download sources for the dependencies.

For instance, I have a dependency

    compile group: 'com.google.gwt', name: 'gwt-dev', version: '2.6.1'

and have tried to `projectName->Dependencies->Download Sources`, but though there are sources for the refered dependency in the expected repository: http://repo2.maven.org/maven2/com/google/gwt/gwt-dev/2.6.1/gwt-dev-2.6.1-sources.jar, NetBeans doesn't download the sources.

I'm not sure if this is a bug, or if I'm missing something. And if the former, I'm not sure that it can be fixed here? @kelemen Perhaps it belongs to https://github.com/kelemen/netbeans-gradle-project?

**Comment by kelemen** [comment]
The download sources is completely done by the core plugin. There is nothing the EE plugin should do about them. Anyway, the plugin just asks Gradle to get the idea model which will actually download the sources if configured so (and it is configured so by default).

There are two things I can think of:

1. You have configured the idea plugin not to download sources (I find this unlikely).
2. You have another repo configured before `mavenCental()` and it contains that dependency without the sources. In this case, you have to reorder the repository order. The most likely candidate is to have `mavenLocal` listed. If so, just remove `mavenLocal`, in most cases it is pointless to have.

**Comment by gallardo** [comment]
Thanks for your answer.

> You have configured the idea plugin not to download sources (I find this unlikely).

You're right: I didn't set up the `idea` plugin, nor any of its options. By the way, I'm using gradle 2.6 and according to the wiki, I thought that [the netbeans-gradle plugin no longer relies on the `idea` plugin of Gradle](https://github.com/kelemen/netbeans-gradle-project/wiki/Build-Script-Parsing#build-script-evaluation-strategy).

>     You have another repo configured before mavenCental() [...]

Unfortunately, the build script I'm working with is extremely complex, and though I have tried to set mavenCentral as the first repository, I'm still not sure that this is not overridden somewhere else... I'm taking a deeper look into it, and I'll report my findings.

In the meanwhile, I'm also trying to reproduce this problem with a simpler build.gradle.

**Comment by kelemen** [comment]
If you don't have the idea plugin configured/applied that is fine because by default it will download sources. By the way, this is the only thing the plugin does via the idea plugin.

By the way, you can just list `project.repositories` in a Gradle task to check what repositories are being used.

**Comment by gallardo** [comment]
> By the way, you can just list project.repositories in a Gradle task to check what repositories are being used.

Great! Or almost... I could positively check that NetBeans doesn't download the sources even there is only one repository (MavenRepo, https://repo1.maven.org/maven2/).

For anyone interested, here is the code to list the loaded repositories (thanks @kelemen):

```groovy
task show << {
    println "Buildscript classpath:"
    buildscript.configurations.classpath.each { println it }
    println "Repositories:"
    project.repositories.each { println "Name: " + it.name + "; url: " + it.url }
}
```

After adding this code to the build script, execute `gradle listrepos` and voilà...

**Comment by gallardo** [comment]
@kelemen Download sources doesn't work for a 'Single Gradle Project'.

Environment:
* NetBeans IDE 8.0.2
* Gradle Support 1.3.7
* Gradle 2.6 (explicitly set in Options->Miscellaneous->Gradle->Gradle Installation)

Steps to reproduce:
1. New Project->Gradle->Single Gradle Project
2. Add dependency `compile group: 'com.google.gwt', name: 'gwt-dev', version: '2.6.1'` to `dependencies`
3. Right click in Projects->Project Name->Dependencies->Download Sources

Should I better close this issue here and move it upstream?

Disclaimer: I'm still pretty new to Gradle (apparently I'll be for a very long time), and cannot be sure that I'm doing things the expected way...

**Comment by gallardo** [comment]
Uhmmm, the `Download sources` doesn't work for the simplest case: fresh created `Single Gradle Project` without further dependencies. I'd expect that it fetches the [junit-4.10 sources](http://central.maven.org/maven2/junit/junit/4.10/junit-4.10-sources.jar) upon `Dependencies [Right Click]->Download Sources`.

**Comment by gallardo** [comment]
Wait a sec.... No. I'm browsing the sources. I don't get it. I'm closing this until I understand what's going on!
