### ISSUE TITLE
Netbeans 8.1 support

### ISSUE THREAD

**Issue by dremon** [hildo/netbeans-gradle-javaee-project#21]
Please add support for the new Netbeans 8.1

**Comment by hildo** [comment]
I've rebuilt the plugin using NB 8.1 dependencies, signed the plugin and submitted to the plugin portal for verification.  I'll leave this issue open until verification is passed, but I don't think there's much else to do with this for now.

**Comment by hildo** [comment]
Plugin has been verified and is now available via the Plugin Portal for NetBeans 8.1
